"""model

Revision ID: 5a3315632af3
Revises: 111f922db2ae
Create Date: 2026-05-13 07:37:13.750738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a3315632af3'
down_revision: Union[str, Sequence[str], None] = '111f922db2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_challenge_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_challenge_progress_challenge_id'), 'user_challenge_progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_user_challenge_progress_user_id'), 'user_challenge_progress', ['user_id'], unique=False)
    op.add_column('challenge', sa.Column('task_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('challengesolution', sa.Column('repo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challengesolution', 'repo_url')
    op.drop_column('challenge', 'task_description')
    op.drop_index(op.f('ix_user_challenge_progress_user_id'), table_name='user_challenge_progress')
    op.drop_index(op.f('ix_user_challenge_progress_challenge_id'), table_name='user_challenge_progress')
    op.drop_table('user_challenge_progress')
    # ### end Alembic commands ###
