"""core models

Revision ID: d2f359dd8d05
Revises: 8ecc4b21df9f
Create Date: 2026-04-28 01:34:13.734963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2f359dd8d05'
down_revision: Union[str, Sequence[str], None] = '8ecc4b21df9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('is_free', sa.Boolean(), nullable=False))
    op.add_column('challenge', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('challenge', sa.Column('difficulty', sa.Integer(), nullable=False))
    op.add_column('challenge', sa.Column('discription', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('challenge', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('challenge', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('challenge', sa.Column('last_edited', sa.DateTime(), nullable=False))
    op.drop_column('challenge', 'secret_name')
    op.drop_column('challenge', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('challenge', sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('challenge', 'last_edited')
    op.drop_column('challenge', 'created_at')
    op.drop_column('challenge', 'image_url')
    op.drop_column('challenge', 'discription')
    op.drop_column('challenge', 'difficulty')
    op.drop_column('challenge', 'type')
    op.drop_column('challenge', 'is_free')
    # ### end Alembic commands ###
