"""fix

Revision ID: f33ff101ed02
Revises: d2f359dd8d05
Create Date: 2026-04-29 11:29:23.941930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f33ff101ed02'
down_revision: Union[str, Sequence[str], None] = 'd2f359dd8d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('challenge', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('challenge', 'description')
    # ### end Alembic commands ###
